const rimraf = require('rimraf')
const home = require('os').homedir()
const { join } = require('path')

rimraf.sync(join(home, '.ssb-shipyard'))
rimraf.sync(join(home, '.ssb-shipyard-test'))
rimraf.sync(join(home, '.ssb-shipyard-test2'))
rimraf.sync(join(home, '.ssb-shipyard-test3'))
rimraf.sync(join(home, '.ssb-shipyard-test4'))
rimraf.sync(join(home, '.ssb-shipyard-test5'))
rimraf.sync(join(home, '.ssb-shipyard-test6'))
rimraf.sync(join(home, '.ssb-shipyard-test7'))
rimraf.sync(join(home, '.ssb-shipyard-test8'))
rimraf.sync(join(home, '.ssb-shipyard-test9'))
rimraf.sync(join(home, '.ssb-shipyard-test10'))
rimraf.sync(join(home, '.ssb-shipyard-test11'))
